"""create agent hitl tables

Revision ID: 952d13dd86bf
Revises: 936cc28dfdbd
Create Date: 2026-06-06 20:04:24.957025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952d13dd86bf'
down_revision: Union[str, Sequence[str], None] = '936cc28dfdbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_message_id', sa.String(), nullable=False),
    sa.Column('assistant_message_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_command_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('uq_agent_runs_active_conversation', 'agent_runs', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('queued','running','awaiting_approval','resume_queued','resuming')"))
    op.create_table('agent_run_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_events_agent_run_id'), 'agent_run_events', ['agent_run_id'], unique=False)
    op.create_table('approval_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('assistant_message_id', sa.String(), nullable=False),
    sa.Column('interrupt_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'interrupt_id', name='uq_approval_batches_agent_run_interrupt'),
    sa.UniqueConstraint('agent_run_id', 'sequence', name='uq_approval_batches_agent_run_sequence')
    )
    op.create_index(op.f('ix_approval_batches_agent_run_id'), 'approval_batches', ['agent_run_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('approval_batch_id', sa.String(), nullable=False),
    sa.Column('tool_invocation_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_batch_id'], ['approval_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_invocation_id'], ['tool_invocations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_batch_id', 'order_index', name='uq_approval_requests_batch_order')
    )
    op.create_index(op.f('ix_approval_requests_approval_batch_id'), 'approval_requests', ['approval_batch_id'], unique=False)
    op.add_column('message_parts', sa.Column('approval_batch_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_message_parts_approval_batch_id', 'message_parts', 'approval_batches', ['approval_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_message_parts_approval_batch_id', 'message_parts', type_='foreignkey')
    op.drop_column('message_parts', 'approval_batch_id')
    op.drop_index(op.f('ix_approval_requests_approval_batch_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_batches_agent_run_id'), table_name='approval_batches')
    op.drop_table('approval_batches')
    op.drop_index(op.f('ix_agent_run_events_agent_run_id'), table_name='agent_run_events')
    op.drop_table('agent_run_events')
    op.drop_index('uq_agent_runs_active_conversation', table_name='agent_runs', postgresql_where=sa.text("status IN ('queued','running','awaiting_approval','resume_queued','resuming')"))
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
